version: '3'

services:
  zkp_server:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - 50051:50051
    networks:
      - zkp-network
    environment:
      - RUST_LOG=info
    command: ["./zkp_server"]
  zkp_client:
    build:
      context: .
      dockerfile: docker/Dockerfile
    networks:
      - zkp-network

networks:
  zkp-network:
    driver: bridge